Public CONST_LPT_MAIN
Public CONST_LPT_COPYRIGHT
Public CONST_LPT_DEBUG
Public CONST_LPT_SEPARATE_OUTPUT
Public CONST_LPT_TIMEOUT
Public CONST_LPT_REROUTE_LPT1
Public CONST_LPT_REROUTE_LPT2
Public CONST_LPT_VDONGLE
Public CONST_LPT_VDONGLE_ENUM
Public CONST_LPT_VDONGLE_NONE
Public CONST_LPT_VDONGLE_KONTRON

CONST_LPT_MAIN               db 'PRINT', 0
CONST_LPT_COPYRIGHT          db 'vLPT v0.9b - (c) by Kiewitz in 2006', 0
                             db ' - Dedicated to Gerd Kiewitz', 0, 0
CONST_LPT_DEBUG              db 'PRINT_DEBUG', 0
CONST_LPT_SEPARATE_OUTPUT    db 'PRINT_SEPARATE_OUTPUT', 0
CONST_LPT_TIMEOUT            db 'PRINT_TIMEOUT', 0
CONST_LPT_REROUTE_LPT1       db 'PRINT_REROUTE_LPT1', 0
CONST_LPT_REROUTE_LPT2       db 'PRINT_REROUTE_LPT2', 0
CONST_LPT_VDONGLE            db 'PRINT_VIRTUAL_DONGLE', 0
CONST_LPT_VDONGLE_ENUM:
CONST_LPT_VDONGLE_NONE       db 'NONE', 0
CONST_LPT_VDONGLE_KONTRON    db 'KONTRON', 0
