
BOOL MINSTALL_LoadCARDINFO (void);
BOOL MINSTALL_ProcessCARDINFO (void);
BOOL MINSTALL_UseCARDINFOCustomData (PMINSTGRP GroupPtr);
VOID MINSTALL_FillCARDINFOCustomData (PMINSTGRP GroupPtr);
VOID MINSTALL_CleanUpCARDINFO (void);
